import AsyncStorage from "@react-native-async-storage/async-storage";

// 🔗 Base URL for your backend API
const BASE_URL = "https://active-patient.onrender.com/api/member";

/* ------------------------------------------------------------
   ✅ Get relationship types (for dropdowns)
------------------------------------------------------------ */
export async function fetchRelationships() {
  try {
    const token = await AsyncStorage.getItem("token");
    const res = await fetch(`${BASE_URL}/relationships/list`, {
      headers: { Authorization: `Bearer ${token}` },
    });

    // Prevent parsing HTML errors
    const contentType = res.headers.get("content-type") || "";
    if (contentType.includes("text/html")) {
      throw new Error("Invalid API response (HTML instead of JSON)");
    }

    const data = await res.json();
    if (!res.ok) throw new Error(data.error || "Failed to fetch relationships");

    console.log("✅ Relationship list loaded:", data.length);
    return data;
  } catch (err) {
    console.error("❌ fetchRelationships error:", err);
    return [];
  }
}

/* ------------------------------------------------------------
   ✅ Fetch all family members linked to logged-in user
   (Now uses /hierarchy which auto-resolves FAB-{UserID})
------------------------------------------------------------ */
export async function fetchFamilyHierarchy() {
  try {
    const token = await AsyncStorage.getItem("token");
    const res = await fetch(`${BASE_URL}/hierarchy`, {
      headers: { Authorization: `Bearer ${token}` },
    });

    const data = await res.json();
    if (!res.ok) throw new Error(data.error || "Failed to fetch family hierarchy");

    return data;
  } catch (err) {
    console.error("❌ fetchFamilyHierarchy error:", err);
    return [];
  }
}

/* ------------------------------------------------------------
   ✅ Fetch single member by ID
------------------------------------------------------------ */
export async function fetchMemberById(memberId: string) {
  try {
    const token = await AsyncStorage.getItem("token");
    const res = await fetch(`${BASE_URL}/details/${memberId}`, {
      headers: { Authorization: `Bearer ${token}` },
    });

    if (!res.ok) throw new Error("Failed to fetch member details");
    return await res.json();
  } catch (err) {
    console.error("❌ fetchMemberById error:", err);
    return null;
  }
}

/* ------------------------------------------------------------
   ✅ Add a new member (FamilyID auto-generated by backend)
------------------------------------------------------------ */
export async function addMember(member: any) {
  try {
    const token = await AsyncStorage.getItem("token");
    const res = await fetch(`${BASE_URL}/add`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(member),
    });

    const data = await res.json();
    if (!res.ok) throw new Error(data.message || "Failed to add member");

    return {
      status: "Success",
      message: data.message || "Member added successfully",
      FamilyID: data.FamilyID || null,
    };
  } catch (err) {
    console.error("❌ addMember error:", err);
    return { status: "Error", message: (err as Error).message };
  }
}

/* ------------------------------------------------------------
   ✅ Update existing member
------------------------------------------------------------ */
export async function updateMember(memberId: string, memberData: any) {
  try {
    const token = await AsyncStorage.getItem("token");
    const res = await fetch(`${BASE_URL}/update/${memberId}`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(memberData),
    });

    const data = await res.json();
    if (!res.ok) throw new Error(data.message || "Failed to update member");

    return { status: "Success", message: data.message || "Member updated successfully" };
  } catch (err) {
    console.error("❌ updateMember error:", err);
    return { status: "Error", message: (err as Error).message };
  }
}



/* ------------------------------------------------------------
   ✅ Soft delete member
------------------------------------------------------------ */
export async function deleteMember(memberId: number) {
  try {
    const token = await AsyncStorage.getItem("token");
    const res = await fetch(`${BASE_URL}/${memberId}`, {
      method: "DELETE",
      headers: { Authorization: `Bearer ${token}` },
    });

    const data = await res.json();
    if (!res.ok) throw new Error(data.message || "Failed to delete member");

    return { status: "Success", message: data.message || "Member deleted successfully" };
  } catch (err) {
    console.error("❌ deleteMember error:", err);
    return { status: "Error", message: (err as Error).message };
  }
}
